import { CarouselSlide, Category, Photographer } from './interfaces';

export const CAROUSEL_SLIDES: CarouselSlide[] = [
  {
    id: 1,
    image: 'photo-1519741497674-611481863552',
    label: 'Weddings',
  },
  {
    id: 2,
    image: 'photo-1511895426328-dc8714191300',
    label: 'Family',
  },
  {
    id: 3,
    image: 'photo-1469334031218-e382a71b716b',
    label: 'Editorial',
  },
  {
    id: 4,
    image: 'photo-1504674900247-0877df9cc836',
    label: 'Corporate',
  },
];

export const CATEGORIES: Category[] = [
  { id: 1, label: 'Wedding', image: 'photo-1519741497674-611481863552', from: 280 },
  { id: 2, label: 'Portrait', image: 'photo-1606216794074-735e91aa2c92', from: 195 },
  { id: 3, label: 'Corporate', image: 'photo-1560472355-536de3962603', from: 250 },
  { id: 4, label: 'Family', image: 'photo-1476703993599-0035a21b17a9', from: 195 },
  { id: 5, label: 'Birthday', image: 'photo-1530103862676-de8c9debad1d', from: 150 },
  { id: 6, label: 'Editorial', image: 'photo-1469334031218-e382a71b716b', from: 400 },
  { id: 7, label: 'Maternity', image: 'photo-1492725764893-90b379c2b6e7', from: 195 },
  { id: 8, label: 'Newborn', image: 'photo-1556910103-1c02745aae4d', from: 195 },
];

export const SPECIALTIES = [
  'All',
  'Wedding',
  'Portrait',
  'Corporate',
  'Family',
  'Birthday',
  'Editorial',
  'Maternity',
  'Newborn',
];

export const PRICE_OPTIONS = ['All', 'Under $100', '$100–$300', '$300+'];

export const SORT_OPTIONS = [
  { value: 'rating', label: 'Top Rated' },
  { value: 'price-asc', label: 'Price: Low → High' },
  { value: 'price-desc', label: 'Price: High → Low' },
] as const;

export const PHOTOGRAPHERS: Photographer[] = [
  {
    id: 'p1',
    name: 'Isabelle Fontaine',
    avatar: 'photo-1487412720507-e7ab37603c6f',
    cover: 'photo-1511285560929-80b456fea0bc',
    specialties: ['Wedding', 'Portrait', 'Couples'],
    bio: 'Paris-trained fine art photographer with a signature soft-light editorial style. I believe every wedding and portrait session deserves to feel like a still from your favourite film — golden, real, unhurried.',
    experience: 9,
    rating: 4.9,
    reviewCount: 214,
    location: 'New York, NY',
    startingPrice: 320,
    featured: true,
    portfolio: [
      {
        id: 'po1',
        image: 'photo-1519741497674-611481863552',
        category: 'Wedding',
        alt: 'Bride in golden light',
      },
      {
        id: 'po2',
        image: 'photo-1606216794074-735e91aa2c92',
        category: 'Portrait',
        alt: 'Editorial portrait',
      },
      {
        id: 'po3',
        image: 'photo-1583939003579-730e3918a45a',
        category: 'Wedding',
        alt: 'Couple ceremony kiss',
      },
      {
        id: 'po4',
        image: 'photo-1529636798458-92182e662485',
        category: 'Couples',
        alt: 'Couple in sunset field',
      },
      {
        id: 'po5',
        image: 'photo-1494790108377-be9c29b29330',
        category: 'Portrait',
        alt: 'Studio portrait',
      },
      {
        id: 'po6',
        image: 'photo-1465495976277-4387d4b0b4c6',
        category: 'Wedding',
        alt: 'Wedding reception details',
      },
    ],
    packages: [
      {
        id: 'pk1',
        name: 'Portrait Session',
        price: 320,
        duration: '1.5 hrs',
        description: 'Single-location portrait or couples shoot',
        includes: ['40 edited photos', 'Private gallery', '2 print credits'],
      },
      {
        id: 'pk2',
        name: 'Wedding Half-Day',
        price: 1800,
        duration: '6 hrs',
        description: 'Getting ready through first dance',
        includes: [
          '500+ edited photos',
          'Online gallery (1 yr)',
          'USB keepsake',
          'Engagement session',
        ],
      },
      {
        id: 'pk3',
        name: 'Wedding Full-Day',
        price: 2900,
        duration: '10 hrs',
        description: 'Complete wedding day coverage',
        includes: [
          '900+ edited photos',
          'Online gallery (3 yrs)',
          'Luxury USB + prints',
          'Engagement + bridal session',
          'Second shooter',
        ],
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Mara & James Collins',
        avatar: 'photo-1438761681033-6461ffad8d80',
        rating: 5,
        date: '2025-06-10',
        text: "Isabelle captured every emotion we didn't even know we were feeling. Our wedding photos are beyond anything we dreamed of.",
        service: 'Wedding Full-Day',
      },
      {
        id: 'r2',
        author: 'Priya Nair',
        avatar: 'photo-1534528741775-53994a69daeb',
        rating: 5,
        date: '2025-05-22',
        text: 'I was so nervous for my headshots but Isabelle made me feel completely at ease. The results are stunning.',
        service: 'Portrait Session',
      },
    ],
  },
  {
    id: 'p2',
    name: 'Marcus Webb',
    avatar: 'photo-1507003211169-0a1dd7228f2d',
    cover: 'photo-1540575467063-178a50c2df87',
    specialties: ['Corporate', 'Events', 'Headshots'],
    bio: 'Commercial and corporate photographer serving Fortune 500 clients and growing startups alike. Clean, contemporary imagery that communicates professionalism and brand identity at a glance.',
    experience: 12,
    rating: 4.8,
    reviewCount: 178,
    location: 'San Francisco, CA',
    startingPrice: 250,
    featured: true,
    portfolio: [
      {
        id: 'po1',
        image: 'photo-1560472355-536de3962603',
        category: 'Corporate',
        alt: 'Corporate headshot',
      },
      {
        id: 'po2',
        image: 'photo-1515187029135-18ee286d815b',
        category: 'Events',
        alt: 'Conference event coverage',
      },
      {
        id: 'po3',
        image: 'photo-1522202176988-66273c2fd55f',
        category: 'Corporate',
        alt: 'Team photo',
      },
      {
        id: 'po4',
        image: 'photo-1559136555-9303baea8ebd',
        category: 'Headshots',
        alt: 'Professional headshot',
      },
      {
        id: 'po5',
        image: 'photo-1497366216548-37526070297c',
        category: 'Events',
        alt: 'Product launch event',
      },
      {
        id: 'po6',
        image: 'photo-1531058020387-3be344556be6',
        category: 'Events',
        alt: 'Gala event',
      },
    ],
    packages: [
      {
        id: 'pk1',
        name: 'Headshot Session',
        price: 250,
        duration: '1 hr',
        description: 'Professional headshots for individuals or small teams',
        includes: ['20 edited images', '2 background options', 'Same-week delivery'],
      },
      {
        id: 'pk2',
        name: 'Team Portraits',
        price: 680,
        duration: '3 hrs',
        description: 'Up to 10 team members, consistent style',
        includes: ['100+ edited images', 'Brand colour grading', 'Social + print ready files'],
      },
      {
        id: 'pk3',
        name: 'Event Coverage',
        price: 1200,
        duration: '8 hrs',
        description: 'Full conference, product launch, or gala coverage',
        includes: ['600+ edited images', '48-hr turnaround', 'Web gallery + download'],
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Tasha Brennan, CEO Luminary Labs',
        avatar: 'photo-1573497019940-1c28c88b4f3e',
        rating: 5,
        date: '2025-06-01',
        text: 'Marcus delivered a brand photo library that elevated our entire online presence. Fast, professional, and genuinely talented.',
        service: 'Event Coverage',
      },
    ],
  },
  {
    id: 'p3',
    name: 'Aiko Nakamura',
    avatar: 'photo-1544005313-94ddf0286df2',
    cover: 'photo-1476703993599-0035a21b17a9',
    specialties: ['Family', 'Maternity', 'Newborn'],
    bio: 'Specialising in the tender, fleeting moments of early family life. My studio and outdoor sessions are gentle, unhurried, and designed to capture genuine connection — not posed perfection.',
    experience: 7,
    rating: 4.9,
    reviewCount: 312,
    location: 'Austin, TX',
    startingPrice: 195,
    featured: false,
    portfolio: [
      {
        id: 'po1',
        image: 'photo-1476703993599-0035a21b17a9',
        category: 'Family',
        alt: 'Family in meadow',
      },
      {
        id: 'po2',
        image: 'photo-1492725764893-90b379c2b6e7',
        category: 'Maternity',
        alt: 'Maternity portrait',
      },
      {
        id: 'po3',
        image: 'photo-1556910103-1c02745aae4d',
        category: 'Newborn',
        alt: 'Newborn studio shot',
      },
      {
        id: 'po4',
        image: 'photo-1516627145497-ae6968895b74',
        category: 'Family',
        alt: 'Family with children',
      },
      {
        id: 'po5',
        image: 'photo-1569233460038-2ef5a1c7ed38',
        category: 'Maternity',
        alt: 'Outdoor maternity',
      },
      {
        id: 'po6',
        image: 'photo-1555252333-9f8e92e65df9',
        category: 'Newborn',
        alt: 'Newborn with parents',
      },
    ],
    packages: [
      {
        id: 'pk1',
        name: 'Mini Session',
        price: 195,
        duration: '45 min',
        description: 'Quick, sweet session for families and individuals',
        includes: ['25 edited photos', 'Online gallery', '1 print credit'],
      },
      {
        id: 'pk2',
        name: 'Family Session',
        price: 380,
        duration: '2 hrs',
        description: 'Relaxed outdoor or studio family portraits',
        includes: ['75 edited photos', 'Private gallery (1 yr)', '4 print credits'],
      },
      {
        id: 'pk3',
        name: 'Maternity + Newborn Bundle',
        price: 620,
        duration: '2 sessions',
        description: 'Maternity shoot + newborn session within 2 weeks of birth',
        includes: ['120 edited photos', 'Gallery + USB', 'Canvas print included'],
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Sophie & Daniel Park',
        avatar: 'photo-1531746020798-e6953c6e8e04',
        rating: 5,
        date: '2025-06-18',
        text: "Aiko has a magical way of making kids (and anxious parents!) feel at ease. Our family photos are treasures we'll keep forever.",
        service: 'Family Session',
      },
      {
        id: 'r2',
        author: 'Leila Moradi',
        avatar: 'photo-1487412720507-e7ab37603c6f',
        rating: 5,
        date: '2025-05-09',
        text: 'My maternity photos are absolutely breathtaking. Aiko has such a gentle, artistic eye.',
        service: 'Maternity + Newborn Bundle',
      },
    ],
  },
  {
    id: 'p4',
    name: 'Declan Murphy',
    avatar: 'photo-1500648767791-00dcc994a43e',
    cover: 'photo-1414235077428-338989a2e8c0',
    specialties: ['Birthday', 'Events', 'Celebration'],
    bio: "Energy, joy, and colour — that's what I bring to every birthday, graduation, and milestone celebration. From intimate backyard parties to luxury venue events, I document the moments you'll want to relive.",
    experience: 5,
    rating: 4.7,
    reviewCount: 89,
    location: 'Chicago, IL',
    startingPrice: 150,
    featured: false,
    portfolio: [
      {
        id: 'po1',
        image: 'photo-1530103862676-de8c9debad1d',
        category: 'Birthday',
        alt: 'Birthday cake and candles',
      },
      {
        id: 'po2',
        image: 'photo-1464366400600-7168b8af9bc3',
        category: 'Events',
        alt: 'Celebration party',
      },
      {
        id: 'po3',
        image: 'photo-1533174072545-7a4b6ad7a6c3',
        category: 'Birthday',
        alt: "Children's birthday party",
      },
      {
        id: 'po4',
        image: 'photo-1496337589254-7e19d01cec44',
        category: 'Events',
        alt: 'Graduation celebration',
      },
      {
        id: 'po5',
        image: 'photo-1578985545062-69928b1d9587',
        category: 'Birthday',
        alt: 'Adult birthday celebration',
      },
      {
        id: 'po6',
        image: 'photo-1519671482749-fd09be7ccebf',
        category: 'Events',
        alt: 'Anniversary party',
      },
    ],
    packages: [
      {
        id: 'pk1',
        name: '2-Hour Coverage',
        price: 150,
        duration: '2 hrs',
        description: 'Perfect for small birthday parties and intimate gatherings',
        includes: ['60 edited photos', 'Online gallery', '48-hr delivery'],
      },
      {
        id: 'pk2',
        name: 'Half-Day Party',
        price: 320,
        duration: '4 hrs',
        description: 'Capture every part of your celebration',
        includes: ['200 edited photos', 'Gallery + download', 'Slideshow video'],
      },
      {
        id: 'pk3',
        name: 'Full Event',
        price: 580,
        duration: '8 hrs',
        description: 'All-day coverage for large events and milestone parties',
        includes: [
          '400+ edited photos',
          'Same-week delivery',
          'Highlight reel video',
          'Print package',
        ],
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Nina Adeyemi',
        avatar: 'photo-1554151228-14d9def656e4',
        rating: 5,
        date: '2025-05-30',
        text: "Declan captured my daughter's first birthday in the most beautiful way. Every little detail was documented. Worth every penny!",
        service: 'Half-Day Party',
      },
    ],
  },
  {
    id: 'p5',
    name: 'Valentina Cruz',
    avatar: 'photo-1531746020798-e6953c6e8e04',
    cover: 'photo-1502904550040-7534597429ae',
    specialties: ['Portrait', 'Fashion', 'Editorial'],
    bio: 'Bold, graphic editorial photography for brands, artists, and individuals who want imagery with attitude. My work has been featured in Vogue España, i-D, and over 30 independent publications.',
    experience: 11,
    rating: 4.8,
    reviewCount: 156,
    location: 'Los Angeles, CA',
    startingPrice: 400,
    featured: true,
    portfolio: [
      {
        id: 'po1',
        image: 'photo-1469334031218-e382a71b716b',
        category: 'Fashion',
        alt: 'High fashion editorial',
      },
      {
        id: 'po2',
        image: 'photo-1509631179647-0177331693ae',
        category: 'Portrait',
        alt: 'Dramatic studio portrait',
      },
      {
        id: 'po3',
        image: 'photo-1515886657613-9f3515b0c78f',
        category: 'Fashion',
        alt: 'Model outdoor shoot',
      },
      {
        id: 'po4',
        image: 'photo-1496747611176-843222e1e57c',
        category: 'Editorial',
        alt: 'Editorial lookbook',
      },
      {
        id: 'po5',
        image: 'photo-1524504388940-b1c1722653e1',
        category: 'Portrait',
        alt: 'Close-up portrait',
      },
      {
        id: 'po6',
        image: 'photo-1487412720507-e7ab37603c6f',
        category: 'Fashion',
        alt: 'Street fashion',
      },
    ],
    packages: [
      {
        id: 'pk1',
        name: 'Creative Portrait',
        price: 400,
        duration: '2 hrs',
        description: 'Expressive, styled portrait session with full creative direction',
        includes: ['50 edited images', 'Mood board collaboration', '2 look changes'],
      },
      {
        id: 'pk2',
        name: 'Editorial Shoot',
        price: 950,
        duration: 'Full day',
        description: 'Magazine-quality editorial for brands or personal projects',
        includes: ['150+ edited images', 'Stylist coordination', 'Usage licence', 'BTS video'],
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Jordan Reeves',
        avatar: 'photo-1507003211169-0a1dd7228f2d',
        rating: 5,
        date: '2025-06-25',
        text: 'Valentina is a true artist. She understood my creative vision instantly and the results were beyond my expectations.',
        service: 'Creative Portrait',
      },
    ],
  },
  {
    id: 'p6',
    name: 'Samuel Osei',
    avatar: 'photo-1506794778202-cad84cf45f1d',
    cover: 'photo-1514306191717-452ec28c7814',
    specialties: ['Wedding', 'Cultural', 'Documentary'],
    bio: 'Documentary-style wedding and cultural ceremony photographer. I believe in watching first, shooting second — letting stories unfold naturally rather than manufacturing moments.',
    experience: 8,
    rating: 4.7,
    reviewCount: 97,
    location: 'Atlanta, GA',
    startingPrice: 280,
    featured: false,
    portfolio: [
      {
        id: 'po1',
        image: 'photo-1519225421980-715cb0215aed',
        category: 'Wedding',
        alt: 'Traditional ceremony',
      },
      {
        id: 'po2',
        image: 'photo-1567633752046-d1ae8b07b406',
        category: 'Cultural',
        alt: 'Cultural celebration',
      },
      {
        id: 'po3',
        image: 'photo-1605100804763-247f67b3557e',
        category: 'Wedding',
        alt: 'Wedding reception candid',
      },
      {
        id: 'po4',
        image: 'photo-1591604466107-ec97de577aff',
        category: 'Documentary',
        alt: 'Documentary style',
      },
      {
        id: 'po5',
        image: 'photo-1513278974582-3e1b4a4fa21e',
        category: 'Cultural',
        alt: 'Cultural portrait',
      },
      {
        id: 'po6',
        image: 'photo-1465495976277-4387d4b0b4c6',
        category: 'Wedding',
        alt: 'Wedding details',
      },
    ],
    packages: [
      {
        id: 'pk1',
        name: 'Ceremony Coverage',
        price: 280,
        duration: '3 hrs',
        description: 'Ceremony + post-ceremony portraits',
        includes: ['150 edited images', 'Online gallery', '2-week delivery'],
      },
      {
        id: 'pk2',
        name: 'Full Wedding Documentary',
        price: 2200,
        duration: '10 hrs',
        description: 'Complete documentary wedding coverage',
        includes: ['800+ edited images', 'Short film (5–8 min)', 'Gallery + USB', 'Second shooter'],
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Amara & Kwame Boateng',
        avatar: 'photo-1580489944761-15a19d654956',
        rating: 5,
        date: '2025-06-05',
        text: 'Samuel understood the significance of every moment in our Ghanaian-American wedding. His documentary approach captured our story with so much respect and beauty.',
        service: 'Full Wedding Documentary',
      },
    ],
  },
];
